config/routes.rb
Rails.application.routes.draw do
  resources :appztbles

end

app/models/appztble.rb
class Appztble < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appztbles_controller.rb
class AppztblesController < ApplicationController
  before_action :set_appztble, only: [:show, :edit, :update, :destroy]

  # GET /appztbles
  # GET /appztbles.json
  def index
    @appztbles = Appztble.all
  end

  # GET /appztbles/1
  # GET /appztbles/1.json
  def show
  end

  # GET /appztbles/new
  def new
    @appztble = Appztble.new
  end

  # GET /appztbles/1/edit
  def edit
  end

  # POST /appztbles
  # POST /appztbles.json
  def create
    @appztble = Appztble.new(appztble_params)

    respond_to do |format|
      if @appztble.save
        format.html { redirect_to @appztble, notice: 'Appztble was successfully created.' }
        format.json { render :show, status: :created, location: @appztble }
      else
        format.html { render :new }
        format.json { render json: @appztble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appztbles/1
  # PATCH/PUT /appztbles/1.json
  def update
    respond_to do |format|
      if @appztble.update(appztble_params)
        format.html { redirect_to @appztble, notice: 'Appztble was successfully updated.' }
        format.json { render :show, status: :ok, location: @appztble }
      else
        format.html { render :edit }
        format.json { render json: @appztble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appztbles/1
  # DELETE /appztbles/1.json
  def destroy
    @appztble.destroy
    respond_to do |format|
      format.html { redirect_to appztbles_url, notice: 'Appztble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appztble
      @appztble = Appztble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appztble_params
      params.require(:appztble).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appztbles_helper.rb
module AppztblesHelper
end

app/views/appztbles/_form.html.erb
<%= form_for(@appztble) do |f| %>
  <% if @appztble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appztble.errors.count, "error") %> prohibited this appztble from being saved:</h2>

      <ul>
      <% @appztble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appztbles/edit.html.erb
<h1>Editing Appztble</h1>

<%= render 'form' %>

<%= link_to 'Show', @appztble %> |
<%= link_to 'Back', appztbles_path %>

app/views/appztbles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>aListing Appztbles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appztbles.each do |appztble| %>
      <tr>
        <td><%= appztble.name %></td>
        <td><%= link_to 'Show', appztble %></td>
        <td><%= link_to 'Edit', edit_appztble_path(appztble) %></td>
        <td><%= link_to 'Destroy', appztble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appztble', new_appztble_path %>

app/views/appztbles/new.html.erb
<h1>New Appztble</h1>

<%= render 'form' %>

<%= link_to 'Back', appztbles_path %>

app/views/appztbles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appztble.name %>
</p>

<%= link_to 'Edit', edit_appztble_path(@appztble) %> |
<%= link_to 'Back', appztbles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>